#!/bin/bash
cd $(pwd)
python3 -m pip install --upgrade pip setuptools virtualenv
python3 -m virtualenv kivy_venv
source kivy_venv/bin/activate
python3 -m pip install kivy[full]
printf %s "1" > q-build
